### ISSUE TITLE
GPS Accuracy is 0 on KIA/HYUNDAI custom integration

### ISSUE THREAD

**Issue by holdestmade** [custom-components/places#118]
I have the KIA/HYUNDAI custom integration installed and the `device_tracker `constantly has a GPS accuracy of 0 so will not allow PLACES to work for that `device_tracker`. Could we add an option, per PLACES integration, to allow for this please as noted in the latest changelog ?

_Add GPS accuracy as attribute and only update the sensor if GPS accuracy is >0 if it exists in https://github.com/custom-components/places/pull/108
If there are devicetracker_ids that work but have GPS Accuracy as 0, this could become an option._

**Comment by Snuffy2** [comment]
Please try v2.2.1 just released. You will want to change the option to Use GPS Accuracy to `False`

**Comment by holdestmade** [comment]
Works perfectly now, many thanks
