### ISSUE TITLE
Request for demo configuration.yaml 

### ISSUE THREAD

**Issue by Kilowatt-W** [custom-components/places#120]
Hello there, thank you for this integration.

I would like to use it, but i cannot figure out how to use all the parameters and how to activate ?

Maybe it would be nice to get a demo configuration.yaml to look at for further information ?

Greetings from Austria

Kilowatt :-)

**Comment by Snuffy2** [comment]
The places integration no longer uses configuration.yaml. It uses the Integrations UI for all of its options. Once installed via HACS, go to Integrations, choose Add Integration and select places. Complete the fields there. There are more details about the settings on the [main places page](https://github.com/custom-components/places).

It looks like I do need to update the install instructions to be more clear. Will work on that.
