### ISSUE TITLE
Building, House in state

### ISSUE THREAD

**Issue by broyuken** [custom-components/places#123]
Why does this component say House 123 Fake St. or Building 123 Fake St. when it should just say 123 Fake St.

**Comment by Snuffy2** [comment]
What do you have in your Options line?

**Comment by broyuken** [comment]
Display options? Formatted_place

**Comment by Snuffy2** [comment]
Yes, that is how formatted_place is designed. If its not a road and there isn't an actual place name (ex. McDonalds) but there is a place type or place category it will show that instead.

**Comment by broyuken** [comment]
I would say either have formatted place not have the category in there, or give a custom field where we can input a list of attributes, maybe comma separated that we want the state to show. That way we can have it show exactly what we want.

**Comment by Snuffy2** [comment]
Yes, you can set your own display options in the config flow. Just type them into the text box. The drop downs are just some common choices to start with.
You can use any of: driving, zone or zone_name, place, place_name, street_number, street, city, county, state, postal_code, country, formatted_address, do_not_show_not_home

**Comment by broyuken** [comment]
How would I do it so that there’s a place name if it exists, but if there isn’t, it shows the address. Pretty much the same logic you use for formatted place minus the category. I have no use for the category in the state.

**Comment by Snuffy2** [comment]
Yeah, that's the issue. The Display Options as they currently stand, don't handle logic. The formatted_place is what I built to show the state how I like it to display. I totally get that it won't be exactly what others want. I'd like to expand the Display Options functionality to support more logic but I've not yet come up with a good syntax that would work and ideally not break the existing simple Display Options.

One thought would be to add optional brackets to the options. If there are brackets after a field and the field is blank/None, display the field(s) in the brackets. These could be nested. But, there are likely many, many permutations and I'm not sure the single logic of "if blank" is really enough.

Example 1:
```
place_name: None
place_type:  Retail
place_category: Building
street_number: 123
street: Main St
city: Los Angeles
state_abbr: CA

Display Options: place_name[street_number, street], city, state_abbr
State: 123, Main St, Los Angeles, CA\
```

Example 2:
```
place_name: McDonalds
place_type:  Retail
place_category: Building
street_number: 123
street: Main St
city: Los Angeles
state_abbr: CA

Display Options: place_name[street_number, street], city, state_abbr
State: McDonalds, Los Angeles, CA
```

Example 3:
```
place_name: None
place_type:  Retail
place_category: Building
street_number: 123
street: Main St
city: Los Angeles
state_abbr: CA

Display Options: place_name[place_type[place_category[street_number, street]]], city, state_abbr
State: Retail, 123, Main St, Los Angeles, CA
```

**Comment by broyuken** [comment]
That would be great if other people would find it helpful as well and I think it would go a long way to making this more useful to other people.

In the meantime would it be possible to just add another, possibly hidden option to display the formatted place without the category and type. Maybe call it simple_formated_place or something? That way it’s available for people to use until you can come up with a way to customize it more and it doesn’t clutter the interface. I’d be more than happy to test this and/or the new logic with you.

**Comment by broyuken** [comment]
Please let me know if this is something you'd entertain, and if there's anything I could do to help test it.

**Comment by Snuffy2** [comment]
I plan to build out the optional bracket logic I had explained above. No eta on when I'll get to it. I'll absolutely take your assistance in testing.

**Comment by Snuffy2** [comment]
I just released Beta v2.2.1.1 with the new Advanced Display Options. If you'd like to test it out, please install the beta. 
[How to enable beta versions for an integration in HACS](https://hacs.xyz/docs/faq/beta/)

See the usage instructions in the beta readme: https://github.com/custom-components/places/blob/adv_display_opt/README.md

I'd also request that you [enable debug logging](https://github.com/custom-components/places/blob/master/CONTRIBUTING.md#enable-debug-logging-in-home-assistant) and send any logs along if you find any issues. Note that there is currently a lot of debug logging currently enabled that will be turned down once it is out of beta.

**Comment by broyuken** [comment]
So far from my little bit of testing Ive done this is doing exactly what I was hoping it would.

**Comment by Snuffy2** [comment]
[v2.3 is released](https://github.com/custom-components/places/releases/latest)
