### ISSUE TITLE
Neighbourhood display option doesn't work

### ISSUE THREAD

**Issue by Elu43** [custom-components/places#130]
Hello,

Neighbourhood display option doesn't work, when I look at the attributes I have the correct neighbourhood, but when i choose to display it with display_options "neighborhood", it shows "Unknown" on my card.

Log displays :

2022-12-23 23:07:59.964 WARNING (SyncWorker_2) [custom_components.places.sensor] (localisation_xxxx) New State is None

**Comment by Snuffy2** [comment]
I just tested it and it is working on my end. What is the full string of attributes in your display_options?

**Comment by SvbZ3r0** [comment]
I've no idea why I'm tagged here. The only thing I did was to sync my waaaay outdated fork to this one.
