### ISSUE TITLE
Event data for places_state_update exceed maximum size of 32768 bytes.

### ISSUE THREAD

**Issue by vlad36N** [custom-components/places#158]
The problem

After upgrade to HA 2023.4.0 and 2023.4.1 have error:

Home Assistant 2023.4.1
Supervisor 2023.04.0
Operating System 9.5
Frontend 20230406.1 - latest

Logger: homeassistant.components.recorder.db_schema
Source: components/recorder/db_schema.py:335
Integration: Recorder (documentation, issues)
First occurred: 9:51:48 AM (1 occurrences)
Last logged: 9:51:48 AM

Event data for places_state_update exceed maximum size of 32768 bytes. This can cause database performance issues; Event data will not be stored

I did open issues on https://github.com/home-assistant/core/issues/91042.
It's closed by [elupus](https://github.com/elupus), stating: This is an issue with a custom component: https://github.com/custom-components/places it needs to be reported there.

**Comment by Snuffy2** [comment]
This is due to a change in 2023.3:
https://github.com/home-assistant/core/pull/90747

Do you have Extended Attributes enabled on the Places Sensor?

I'll need to sort out how to either exclude it from the recorder or remove some data from the event.

**Comment by vlad36N** [comment]
Hi,

Yes, Extended Attributes is enabled.


![places](https://user-images.githubusercontent.com/30022288/230974078-6f8ae903-bcd8-433c-8ffa-3da05175d43a.png)
