### ISSUE TITLE
1 of 3 device integration not update

### ISSUE THREAD

**Issue by et-non** [custom-components/places#167]
I have 3 device but got problem my 1 of 3 device not update still unknown in home assistant

My system 
Home Assistant 2023.4.6
Operating System 10.0
traccar integration

I tried remove and add, but no luck still unknown.

![Screenshot 2023-04-22 172658](https://user-images.githubusercontent.com/65827366/233778480-d5e5e778-9549-4ada-b33b-86c1bfac9c41.jpg)

**Comment by Snuffy2** [comment]
In the rest of the Attributes for that places sensor, what is the value for GPS Accuracy? If it is 0, does it always stay at 0 even when the location is changing? If so, go into the Options for that one and Set Use GPS Accuracy to False.

In device_trackers that correctly update GPS Accuracy, places wont update the location when GPS Accuracy is 0. However, some device_trackers seem to report GPS Accuracy of 0 no matter what.

**Comment by et-non** [comment]
Thank you, that solve the problem.

My 2 device that are working, are android car run with traccar client but other one run sinotrack st-901.
Didn't notice that sinotrack st-901 report GPS Accuracy 0 in home assistant
