### ISSUE TITLE
Connection issues and User-Agent

### ISSUE THREAD

**Issue by dallas6672** [custom-components/places#168]
Anyone else getting Connection Errors with OSM lately? I recently upgraded to the new version that requires the configuring from the UI instead of YAML. Believe I'm using "2.3.4.1" and just noticed there's newer version, 2.3.5. Shortly after I started getting the connection issues with OSM. Although, it doesn't seem like it's a "Places" issue since I've been able to reproduce the timeouts from Browsers and running Python Requests from my PC. I've also tried using VPNs to make sure they weren't rate limiting my home IP for some reason.

I haven't been able to find reports from others having this issue. Even checked the GitHub (https://github.com/openstreetmap/openstreetmap-website/issues) and their help site (https://help.openstreetmap.org/)

This is the error from Home Assistant...

`("SENSOR") Network unreachable error when connecting to OpenStreetMaps [HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /reverse?format=jsonv2&lat="LAT"&lon="LON"&accept-language=en&addressdetails=1&namedetails=1&zoom=18&limit=1&email="EMAIL" (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))]:`

I also tried adding Sessions with Retries which still errors out...

`Retrying (Retry(total=3, connect=3, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))'`

This brings me to the second point about the User-Agent. When I was trying to troubleshoot this, I ran across their Policy. Does Places need to add the User-Agent? (https://operations.osmfoundation.org/policies/nominatim/)

"Provide a valid HTTP Referer or User-Agent identifying the application (stock User-Agents as set by http libraries will not do)"

Here is the code that I added for the User-Agent and Sessions to try helping out with the connection issue...

`
# added these to the imports
            from requests.adapters import HTTPAdapter
            from requests.packages.urllib3.util.retry import Retry

# replaced "get_response = requests.get(url)" with...
            appName = 'Places/2.3.4.1'
            
            headers = {
                "User-Agent": appName
            }
            session = requests.Session()
            retry = Retry(connect=3, backoff_factor=1.5)
            adapter = HTTPAdapter(max_retries=retry)
            session.mount('https://', adapter)
            
            get_response = session.get(url, headers=headers)
`

Another thing that I changed was increasing the "Distance Traveled M" from 10 to 30 since I get the timeout errors even when the devices are stationary, but the Places update still seems to trigger.

For the sensor config, I use OSM for the map. email is set, Display options are "formatted_place, driving" and GPS accuracy is enabled.

**Comment by Snuffy2** [comment]
The OpenStreetMap Nominatim server has had short on and off outages since 4/19. Scroll down to Nominatim HTTPS:
https://uptime.openstreetmap.org/

I've not seen any issue without a User Agent, but per your links it seems like a good idea to add one. I'll add it to the To Do. Thanks.

**Comment by dallas6672** [comment]
Thanks for the find on the uptime status.

As for the updates even when a device is stationary, like at home, I'll just keep adjusting the minimum meters the device needs to travel to limit the false positives. Noticing some that are still higher the 30 m minimum that I had set in my first post...

"Not performing update, distance traveled from last update is less than 40 m (33.7 m)"

**Comment by Snuffy2** [comment]
There is also a second check that happens after this. If it detects distance is greater than XX m, it then gets the location info from OpenStreetMap. If the location info is the same as what is currently set, it also does not trigger a change to the sensor. That step triggers a call to OSM but won't cause the sensor to change unless the data has changed.

**Comment by dallas6672** [comment]
From the behavior I've been noticing since the OSM connection issue started, is at least every 30-60 minutes, a device's location info is trying to be updated from OSM when stationary. 

After turning on the Debugs this morning, they all seem to come from GPS updates where Places sees it moving more than the default 10 m because of a less accurate reading than the previous. Like in my first post I had it set to 30 meters since most of the triggers were Places seeing a device move more than 20 meters. Then I seen some that were in the 30's and that's why I bumped it up to 40.

**Comment by dallas6672** [comment]
Think I've run into an update loop. Doing the same update for a couple of hours now according to the logs. I think this might be caused by a larger than usual "Home" area. I've increased the size to make sure that automation triggered by arriving Home run before actually getting to and into the house.

What I'm seeing in the logs is the device update is getting triggered by the 10 minute Scan Interval. Addon thinks it needs an update because of the meters traveled, 657.9, but then when it checks the States it sees the Previous = New and then doesn't update the new location.

Calling update for device_tracker.iphone due to: Scan Interval
GPS Accuracy: 12.672
Previous State: Home
Previous last_place_name: North St
Previous Place is Zone: Home
last_place_name (Initial): Home
DeviceTracker Zone Name: Home
---Excluding Coordinates---
Distance from home [home]: 0.024 km
Travel Direction: towards home
Meters traveled since last update: 657.9
Meets criteria, proceeding with OpenStreetMap query
DeviceTracker Zone: home
---Excluding Query Data and OSM Dict---
Initial last_place_name is same as new: place_name=None or devicetracker_zone_name=Home, keeping previous last_place_name
last_place_name: North St
New State using formatted_place: Home
No entity update needed, Previous State = New State
Reverting attributes back to before the update started
End of Update

**Comment by Snuffy2** [comment]
A user-agent header is now sent to OpenStreetMaps in places v2.4
