### ISSUE TITLE
Not pulling Tesla Info

### ISSUE THREAD

**Issue by noneabove1182** [custom-components/places#169]
Trying to use this integration with the device_tracker for my tesla which includes Latitude and Longitude attributes, but the sensor never updates with the new info

In the logs it looks like it's attempting to pull the data, but as someone is currently out driving (and I can see the tesla integration lat/long changing) it's still stuck at my house on Places.

Any ideas what I have set up wrong?

**Comment by Snuffy2** [comment]
It looks like the Tesla and Teslamate integrations always report a GPS Accuracy of 0 regardless of how accurate the GPS Accuracy actually is. In the places configuration for this sensor, set `Use GPS Accuracy` to False and it should start working.

**Comment by homecb** [comment]
Was having the same issue and the suggestion above worked. Thank you!
