### ISSUE TITLE
Selector of DeviceTracker ID: fix a sorting method

### ISSUE THREAD

**Issue by ildar170975** [custom-components/places#173]
Entries in the dropdown list are sorted by a "name" - but separately for lowercase & capital letters.
This gives weird results - iPhone & iPad devices are places in the end of list:

![изображение](https://github.com/custom-components/places/assets/71872483/9f4c0476-bb81-41e1-ac1f-8c8bdef950e5)

Proposal - ignore letters' case.

**Comment by Snuffy2** [comment]
device_tracker and zones should now sort case insensitive in the UI in places v2.4

**Comment by ildar170975** [comment]
Thanks a lot!
