### ISSUE TITLE
Created "place" sensor is "unknown"

### ISSUE THREAD

**Issue by ildar170975** [custom-components/places#174]
I have a `person` entity:
![изображение](https://github.com/custom-components/places/assets/71872483/be57eaf5-0aa7-4211-b13c-4a63d1c0e786)

and a corresponding `device_tracker` entity:
![изображение](https://github.com/custom-components/places/assets/71872483/24081604-cbc1-438c-86dc-47a8dcf33ebc)

Just now I created a `place` sensor for this `person`:
core.config_entries:
```
      {
        "entry_id": "e42060691110f4742412aa0bcb2057e4",
        "version": 1,
        "domain": "places",
        "title": "xxxxxxxxx",
        "data": {
          "devicetracker_id": "person.xxxxxxx",
          "api_key": "xxxxx@gmail.com",
          "options": "formatted_address",
          "home_zone": "zone.xxxxxx",
          "map_provider": "google",
          "map_zoom": 19.0,
          "extended_attr": false,
          "show_time": false,
          "use_gps_accuracy": true,
          "name": "xxxxxxxx"
        },
        "options": {},
        "pref_disable_new_entities": false,
        "pref_disable_polling": false,
        "source": "user",
        "unique_id": null,
        "disabled_by": null
      }
```
But the created sensor is `unknown`:
![изображение](https://github.com/custom-components/places/assets/71872483/74d2b87e-b70f-49dc-b5bb-e4e8015167f5)

There is a warning in the Log (probably related to the issue):
Error converting Last Changed date/time (None) into datetime: TypeError('fromisoformat: argument must be str')
![изображение](https://github.com/custom-components/places/assets/71872483/f3bed557-300b-4811-9b8b-37de295a59e8)

**Comment by Snuffy2** [comment]
It looks like the GPS Accuracy might be reporting as 0 regardless of how accurate the GPS Accuracy actually is. In the places configuration for this sensor, set Use GPS Accuracy to False and it should start working.

The code is actually handling when the Warning you listed is being shown and is working around it so I don't think that is causing the issue.

**Comment by Snuffy2** [comment]
You'll have to see if your device uses GPS Accuracy at all or not when you do have signal. There seem to be a number of devices that always report GPS Accuracy of 0 but update their location. And conversely, plenty that accurately update their GPS Accuracy.

**Comment by ildar170975** [comment]
> if your device uses GPS Accuracy at all or not when you do have signal

Seems that `gps_accuracy` is always 0.
Then this is a question to the Starline integration.

Closing the issue.
Thanks a lot for support!
