### ISSUE TITLE
Help with display options

### ISSUE THREAD

**Issue by broyuken** [custom-components/places#177]
Hello, I need some assistance with the display options for places. I'm use the icloud3 custom component and when I stay in one place for a few minutes a dynamic zone gets set called Stationary. I would like to have the zone name display for any zone I am in EXCEPT for the Stationary zone. This is what I currently have set up for the display options.

 driving, name_no_dupe[[category(-, highway)], house_number, route_number(type(+, motorway, trunk))[street[route_number]], neighborhood(type(house))], city[county], state_abbr

**Comment by Snuffy2** [comment]
It should already be excluding any zone that contains "stationary." I use icloud3 as well and it has been working well. 

Note that icloud3 v3 changes the same of its stationary zone to ic3_statzone_# and name StatZon# (with # being optional in the name). In the next `places` release coming soon, I'll account for those as well.

If you're on icloud3 v2 and seeing Stationary listed as the Zone, please [enable debug logging](https://github.com/custom-components/places/blob/master/CONTRIBUTING.md#enable-debug-logging-in-home-assistant) and post the pertinent logs so I can try to better understand what is happening.

**Comment by broyuken** [comment]
Yea I'm on ic3_v3 as well and just noticed the issue when Gary made the changes to the stationary zone. I'm on 16c, so I changed the stationary zone back to stationary from statzon but I was still seeing it show up. If you are aware of this issue I can wait for the next Places update.

**Comment by Snuffy2** [comment]
Yes, I'll detect the new icloud3 v3 default stationary zones with the next update. However, if you changed the stationary zone name in icloud3 v3 to contain the word stationary, `places` should work as the code is set to exclude any zone that contains stationary in the name.

**Comment by Snuffy2** [comment]
icloud3 v3 default stationary zones should now be recognized in places v2.4
