### ISSUE TITLE
Call service to manually update or ignore Home Assistant zone?

### ISSUE THREAD

**Issue by jebissell** [custom-components/places#184]
For a family member who often charges the smartphone in various locations in the city but then forgets the charger, I want to update the nearest POI provided by Places for the phone's current location at the moment charging stops, then send a notification if they depart that location. However to support other automations I have created a zone for the whole city, so there might be multiple locations of interest where the device tracker changes geolocation/address but remains in the same zone. I tried creating a dummy zone outside of all the others and set as home zone in Places, but that doesn't appear to allow getting the latest POI for that location. Is there a Home Assistant call_service command that would force an update, or other way of automatically updating if geolocation changes, but not the zone?.

**Comment by Snuffy2** [comment]
Interesting request. Currently, I don't believe this can be done with `places`. In theory, the [Advanced Display Options](https://github.com/custom-components/places#advanced-display-options) could be modified to also accept Zone as a field like the other fields. Currently, if the `places` sensor is in a Zone, that overrides everything else. It would be a breaking change for those using Advanced Display Options but I don't believe many are using them at this point. Let me think about it and see how much coding changes it will entail.

**Comment by flyrmyr** [comment]
If I'm understanding this correctly I think thats my use case as well. I'm trying to track my home zone (RV) as it moves, and I hacked up a `device_tracker` to update when my home zone does. But in effect that means it's always "home," which I think is making it not want to update.
Per my issue request, would love a `zone` mapper option instead of `device_tracker`.

**Comment by jebissell** [comment]
With the summer travel season arriving, I had to come up with my own solution that may be useful for the RV scenario:

Preparation:
- Determine multiple zones in HA that count as "unofficial home" (3 in my case)
- Set up command line sensor in HA, a curl call to the Openstreetmap nominate API that presents X,Y coordinates to the API and captures the nearest POI returned for those coordinates

Use:
1. Home Assistant Companion App senses phone charging start, and triggers an automation storing the X,Y coordinates of the phone and the resolved street address into one input helper each (all data provided by Companion App sensor attributes
2. When charging stops, store the POI as returned by Openstreetmap in its own input helper
3. Once the phone has traveled beyond 0.5 km from charging X,Y, and the charging X,Y wasn't the HA Home zone or one of the zones designated as "virtual home", then send a push alert to the phone advising where the phone was last charging.

There's a further delay added before detecting charging has begun, since when traveling by train or car there are often intermittent dropouts in train and bus USB plug charging current (generating repeated charging restart events) or dropouts in wireless coverage. This limits the Openstreetmap API calls to a minimum. Also, the notification message shows both the street address and the nearest POI, but omits the POI if the same as the street address--often the case in outlying areas.

Maybe this approach is helpful for thinking about further development.

**Comment by Snuffy2** [comment]
You should now be able to accomplish what you are looking to do with v2.4.4 just released. You will need to use the Advanced Display Options. Let me know how it goes.
