### ISSUE TITLE
Repeated information on UI

### ISSUE THREAD

**Issue by vlad36N** [custom-components/places#188]
Hi,

After last update to v2.4.3, repeated information on UI.

Rebooted HA many times, refresh pages not helping. 

![places](https://github.com/custom-components/places/assets/30022288/a5d25fb9-9f17-455f-b74e-77729ee28dcd)

Home Assistant 2023.7.3
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.1 - latest

No log entries .

Thank you.

**Comment by Snuffy2** [comment]
I'm not seeing this on my end. What are the Display Options for that places sensor?

**Comment by vlad36N** [comment]
In ui-lovelace.yaml file:

      - type: custom:vertical-stack-in-card
        title: Family
        cards:
          - type: entities
            entities:
              - entity: sensor.inna
              - entity: sensor.vlad

Now repeated info gone. didn't change or touch anything.
Thank you.
