### ISSUE TITLE
If there is no address info set, still run the update even if distance traveled is below limit

### ISSUE THREAD

**Issue by flyrmyr** [custom-components/places#189]
Love the function of this integration, but it misses heavily for me in certain ways.

The service doesn't perform an update if the distance traveled is less than a certain amount, good call. But most of the time it also doesn't manage to set the value initially, so I get stuck with no address info and then it refuses to update unless I reload the integration. Hoping to add a check where it will still call the API to set address info, even if distance traveled is below the limit, in cases where it has not already queried and set the address.

This may be due to the fact that my "device" never leaves the "home" zone. I have a van/rv, and I was hoping to use this to track where "home" is, but sadly its very device vs. home zone oriented, and theres no way to track an actual zone. So I created a mock `device_tracker` that updates from my home zone, to get that address. Perhaps we could add the zone tracking functionality for those of us (theres definitely a handful) who would benefit from that, instead of tracking a device away from home.

**Comment by Snuffy2** [comment]
Adding the ability to track the location of a zone is a relatively trivial change. If you'd like to test it out before I'm able to add it into a release, open up `/custom_components/places/const.py` and add zone to TRACKING_DOMAINS that starts on line 29:

```
TRACKING_DOMAINS = [
    str(Platform.DEVICE_TRACKER),
    str("person"),
    str(Platform.SENSOR),
    "variable",
    "zone", 
]
```

As you pointed out though, the `places` zone sensor will always report that zone as its location. Since it has been requested here and in #184, I'll work on updating the [Advanced Display Options](https://github.com/custom-components/places#advanced-display-options) to make whether Zone shows a configurable option. No ETA.

Out of curiosity, how are you auto-updating the zone's location when you drive the RV to a different location?

**Comment by flyrmyr** [comment]
Oh cool thanks, I'd love that in a release but I'll play around a bit and see if I can get that working in the meantime!

For my Home zome, I have a GPS dongle in my Pi4, running this 3rd party [GPSD Add-on](https://github.com/corvy/ha-addons/tree/main/gpsd2mqtt) which uses mqtt to update a device tracker "gps_location." My automation watches for those changes and updates the Home zone with the script below:

```
- id: location
  alias: Monitor GPS Location
  trigger:
  - platform: state
    entity_id:
    - device_tracker.gps_location
  condition: []
  action:
  - service: homeassistant.set_location
    data_template:
      latitude: '{{ state_attr(''device_tracker.gps_location'', ''latitude'') }}'
      longitude: '{{ state_attr(''device_tracker.gps_location'', ''longitude'') }}'
```

I use this for solar forecasting, weather etc. Hiccups are, haven't figured out how to make it keep a zone location history, so I have to map both my `gps_location` and my `zome.home` to get the home icon and the X hrs location history.

Not sure if its of interest to you and this integration, but I added some custom URL links for Google/Apple maps to Van, and Uber/Lyft to Van, that all open a pre-destinated route home at a click which is really nice (and simple) you just need to create an "app" to get a `private_key` through the rideshare services.

My one concern with the zone tracking you mentioned is, is there something preventing my address from updating if the device being tracked hasn't left its zone? I've never been able to get the address to load without running `reload` on the integration, then it always shows up immediately. But it disappears if I change locations. The logs show its updating every few seconds, but "hasn't moved" so it bypasses the update...

**Comment by Snuffy2** [comment]
You should now be able to accomplish what you are looking to do with v2.4.4 just released. You will need to use the Advanced Display Options. Let me know how it goes.
