### ISSUE TITLE
last updated feature ignores HASS timezone

### ISSUE THREAD

**Issue by aradng** [custom-components/places#209]
Hi,
current **Show last updated time at end of state** feature uses **datetime.now()** module which returns GMT by default. would be great to add tz aware functionality from the HASS's own tz or manualy set tz.

**Comment by Snuffy2** [comment]
It actually uses the system's tz if it is set. If you are seeing GMT then yours likely isn't set. I'll look to have it use the HASS tz in the next version though, that is a good idea!
