### ISSUE TITLE
2.5 update breaks integration

### ISSUE THREAD

**Issue by johnwalk61** [custom-components/places#221]
I updated to the new 2.5 version. Places doesn't get any information and nothing in the logs.
I reverted to 2.4.5 and it is working again.

Tried several times to update and had to revert each time.

Fantastic integration BTW.

Cheers

**Comment by Snuffy2** [comment]
Interesting. Not seeing any issues here, but obviously something that changed is breaking it for you. If you're not seeing anything in the normal logs, can you please [enable debug logging](https://github.com/custom-components/places/blob/master/CONTRIBUTING.md#enable-debug-logging-in-home-assistant) and post them here please.

**Comment by johnwalk61** [comment]
I added the debugging and for some reason today when I updated it started working.
You can close the issue. Not sure why it wasn't getting locations for my devices before.

Cheers
John
