### ISSUE TITLE
Make scan interval configurable

### ISSUE THREAD

**Issue by carefulcomputer** [custom-components/places#236]
I see following values in the code

```
THROTTLE_INTERVAL = timedelta(seconds=600)
MIN_THROTTLE_INTERVAL = timedelta(seconds=10)
SCAN_INTERVAL = timedelta(seconds=30)
```

Can you please make the scan internal (I am assuming it will call OSM every 30 seconds. Several people do not need this high resolution. Are you able to make the scan interval configurable ? For example, for my needs 5 mins is sufficient

**Comment by Snuffy2** [comment]
SCAN_INTERVAL is not being used in the code.
MIN_THROTTLE_INTERVAL of 10 seconds is set to prevent `places` from querying the OpenStreetMaps server more than once every 10 seconds.
THROTTLE_INTERVAL of 10 minutes is the time to see if there have been any updates even if the tracked entity hasn't changed.

The `places` update logic is as follows:
**First:**
* `places` will start an update whenever the tracked entity changes (but only at most once every 10 seconds) 
* It will also start an update every 10 minutes even if no tracked entity changes. 

**Then:**
* If the tracked entity coordinates are identical from previous to now, the update stops
* If the coordinates are different but the distance is <10m, the update stops
* If the distance is >10m it will requery OSM
* If the previous state = new state, the update stops
* If it gets to here, the full update is run and an event is fired

**Comment by carefulcomputer** [comment]
If try to correlate it in real world terms, if a person is stationary then OSM will be called every 10 minutes. If they are moving (e.g. in a car) then it will update every 10 seconds. 
Though much better than what I had assumed (not every 30 seconds), do you think it will be useful to make both of these numbers configurable ? Several people (like me) would not want update more frequent than 5 mins (even if moving) and maybe 20 mins if not moving. We can always default the values to what is already in the code.
