### ISSUE TITLE
[FR] Allow typing in the "Tracked Entity ID" selector to define a pattern

### ISSUE THREAD

**Issue by ildar170975** [custom-components/places#239]
Currently a user needs to select an entity from a dropdown list:

![изображение](https://github.com/custom-components/places/assets/71872483/259e7514-266b-4529-94a1-dd136025efbf)

The list may be rather long.
Propose to add a possibility to input a pattern - like it is implemented for a standard Entities card:

![изображение](https://github.com/custom-components/places/assets/71872483/065b4324-43dd-459c-8c1a-9c927cfd262c)

**Comment by Snuffy2** [comment]
@ildar170975 you had requested to move away from the entities selector in #55. The entity selector allows the searching like you are looking for, but then only shows the friendly same once it is selected. The Select Selector that allows me to show both the friendly name and the entity id doesn't support searching like the entity selector does.

https://www.home-assistant.io/docs/blueprint/selectors/

**Comment by ildar170975** [comment]
> you had requested to move away from the entities selector in #55

I requested to move away from a selector which shows a `friendly_name` in the input field:
![191165142-e1ee3073-fe6b-4f3e-b67a-dda63af5995e](https://github.com/custom-components/places/assets/71872483/e7673827-a218-46f6-9063-6c6ff48f9f57)

The reason was:
there are many entities with same `friendly_name` - and looking at the input field it is impossible to guess which entity is selected.

Then you created a dropdown list with displaying both `entity_id` & `friendly_name`:
![изображение](https://github.com/custom-components/places/assets/71872483/1d80fea3-8dda-463d-8dbd-1fded399d089)
This is a 100% clear presentation - a user can see exactly which entity is selected.

The [standard entity selector](https://www.home-assistant.io/docs/blueprint/selectors/#entity-selector) gives a clear list of entities in a list:
![изображение](https://github.com/custom-components/places/assets/71872483/b5f7dd91-0e54-4166-8034-82052f5d57dc)
but an unclear result:
![изображение](https://github.com/custom-components/places/assets/71872483/e98c343b-b907-4507-9ba0-3dda2019f322)
So - the standard selector itself is not useful enough(((

I wonder is it possible to create a custom selector (like you already did) which:
1. Have a clear result - as it does now:
![изображение](https://github.com/custom-components/places/assets/71872483/1d80fea3-8dda-463d-8dbd-1fded399d089)
2. Have a clear list of entities - like it does now:
![изображение](https://github.com/custom-components/places/assets/71872483/ad0f6d05-88d6-4f4a-93e9-a382b340b074)
3. AND have a possibility to type a pattern to find an `entity_id`?

**Comment by Snuffy2** [comment]
Sorry, I'm not aware of anyway to do this. The only way I can see would be to have Home Assistant update the Select Selector to be able to support searching.

**Comment by ildar170975** [comment]
> Home Assistant update the Select Selector to be able to support searching.

I would say - "to support a clear displaying both `friendly_name` and `entity_id`" - like you did in your custom selector.

Currently the standard HA entity selector displays only `friendly_name`; as for searching - it does searching (but with a weird results cause by recently added "fuzzy search" - [here](https://github.com/home-assistant/frontend/discussions/17474), [here](https://github.com/home-assistant/frontend/issues/17989)).
Not to mention that a selected item is not selected in the list after reopening the list ([here](https://github.com/home-assistant/frontend/issues/17395)), that a previously filtered list becomes unfiltered after reopening ([here](https://github.com/home-assistant/frontend/issues/17473)).
So, there are plenty of bugs in this standard entity selector.

**Comment by ildar170975** [comment]
So, I agree to wait for the standard HA entity selector to be improved & de-bugged.

**Comment by Snuffy2** [comment]
Closing for now pending improvement of HA functionality.

**Comment by ildar170975** [comment]
Agreed
