### ISSUE TITLE
[question] "Places" sensor & Recorder

### ISSUE THREAD

**Issue by ildar170975** [custom-components/places#245]
This issue is not a bug report or a FR - it is mainly a question.

A `places` sensor contains a lot of data in attributes.
I believed that all these attributes stored in database - so I excluded all `places` sensors from Recorder.
But may be no all data stored in DB - and hence there is no need to exclude these sensors?

**Comment by Snuffy2** [comment]
A places sensor writes to the recorder unless Extended Attributes is enabled. In that case, I exclude it as it is larger than what is accepted by the recorder.

**Comment by ildar170975** [comment]
Thank you very much for the answer!

Even w/o "extended attributes" this records seems to be rather huge for me:

![изображение](https://github.com/custom-components/places/assets/71872483/a57044d0-79c3-407a-b757-647142dc72d9)

Most of these data are useful & needed, so I think that in a not-powerful PCs (like RPi) users may decide to exclude the `places` sensors from Recorder.
That is why I created a template sensor for storing a `state` only.
The state keeps either a zone's name or a address (if `not_home`):
![изображение](https://github.com/custom-components/places/assets/71872483/5a262538-78fe-40b8-bb97-6ae12e802492)
Hope this is the right settings for me.
