### ISSUE TITLE
Do not use Nominatim details API 

### ISSUE THREAD

**Issue by lonvia** [custom-components/places#246]
You make automated use of the `/details` endpoint of Nominatim here: https://github.com/custom-components/places/blob/95ca1e20f3db844dd18a86add972a23579d5b7b8/custom_components/places/sensor.py#L1782

Please note that this is not permitted as per [usage policy](https://operations.osmfoundation.org/policies/nominatim/). Your usage is currently low enough that the server can cope but there is no guarantee that you won't get banned without notice in the future.

Have a look at the [lookup](https://nominatim.org/release-docs/develop/api/Lookup/) endpoint. When used with `addressdetails=1`, `extratags=1` and `namedetails=1`, it should get you all the details you could possibly need for a given OSM object. The one thing missing is the hierarchy information but this is unreliable anyway and will be removed soon. If you need something like "all street names in this town", you should have a look at Overpass API.

**Comment by Snuffy2** [comment]
Thank you for letting me know. I'll get `places` transitioned from details to lookup.
