### ISSUE TITLE
Home Assistant warning

### ISSUE THREAD

**Issue by Radushka** [custom-components/places#25]
First off, thank you for this great integration that I use every day!

Any chance you could update it to include the version key in the manifest, as per this recent message from HA:

No 'version' key in the manifest file for custom integration 'places'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'places'.

Thank you.

**Comment by vlad36N** [comment]
Check: https://github.com/custom-components/places/issues/24

**Comment by Radushka** [comment]
Oh, my bad for not checking closed issues. Thank you!
