### ISSUE TITLE
Feature: Link with Coordinates to OSM Online Map

### ISSUE THREAD

**Issue by dabenzel** [custom-components/places#255]
It would be nice to add a Link/Entity for each sensor, that you can directly jump into the OSM Online Map.

Schema of URL would be https://www.openstreetmap.org/?mlat=<LATITUDE>&mlon=<LONGITUDE>

**Comment by Snuffy2** [comment]
Change the Map Provider to OSM and the `map_link` attribute will then be to OpenStreetMaps.

**Comment by Snuffy2** [comment]
Please re-open or start a new Issue if this does not address your needs.
