### ISSUE TITLE
Never shows the city

### ISSUE THREAD

**Issue by markandersonus** [custom-components/places#264]
Looked through all attributes and there isn't even one called city

Maybe I'm missing something but there does not seem to be a way to get something as simple as city, state (e.g. Miami, FL)

**Comment by Snuffy2** [comment]
https://github.com/custom-components/places#configuration-options
Display options: formatted_place (exclusive option), driving (can be used with formatted_place or other options), zone or zone_name, place, place_name, street_number, street, city, county, state, postal_code, country, formatted_address, do_not_show_not_home
