### ISSUE TITLE
JSON temp folder created at wrong location

### ISSUE THREAD

**Issue by ReneNulschDE** [custom-components/places#269]
First of all thanks for this good component. When analyzing a bug report with your and my component, I found a small bug. Should not be critical as most of the users are not running HA in an dev environment...

Problem:
When you start HA out of different folder then the HA-config directory (with -c switch for the config-file) then the json temp-folder gets not created in the config-folder/custom_components/... but at the current location.

Environment:
- HA core latest on ubuntu
- python 3.12 in venv

Steps to Repro:
- Use HA core
- initialize venv
- go to a different folder then .homeassistant
- start ha with hass -c ~/.homeassistant
- Add a sensor
- a new directory custom_components/places/json_sensors is created in the startup folder 

Expected:
json temp folder is created under the HA-config folder

Others:
Potential critical code area: [here](https://github.com/custom-components/places/blob/4952b240fc761b90e30428a29c7339bbf3486c1c/custom_components/places/sensor.py#L152)

Maybe it is better to use hass.config.path() to build the path.

**Comment by Snuffy2** [comment]
Please let me know if v2.6.2 fixes this or not.

**Comment by ReneNulschDE** [comment]
Fixed. Thx
