### ISSUE TITLE
History screen not showing any data

### ISSUE THREAD

**Issue by kmanan** [custom-components/places#279]
Hi. I'm running into an odd issue where the history screen does not show any data other than the current "home" status. here's a screenshot of the geocode sensor and my "person" sensor that show home / away:

Geocode sensor:

![image](https://github.com/custom-components/places/assets/17659155/95cf796d-e85d-41a4-8826-c31c39abf1d0)

![image](https://github.com/custom-components/places/assets/17659155/95bb42b4-0309-46e4-85e1-e62cbe29d80c)

**Comment by booa1986** [comment]
I have the same :(

**Comment by Snuffy2** [comment]
You said you are using a person entity, correct? Are there >1 device_trackers linked to that person and is one of them by chance a router? If so, then what you are probably seeing is that when the person entity is using the router for presence it does not provide GPS coordinates and `places` may not show any location. 

If this is not your scenario, can you please [enable debug logging](https://github.com/custom-components/places/blob/master/CONTRIBUTING.md#enable-debug-logging-in-home-assistant) and post these so I can investigate further.

**Comment by kmanan** [comment]
> You said you are using a person entity, correct? Are there >1 device_trackers linked to that person and is one of them by chance a router? If so, then what you are probably seeing is that when the person entity is using the router for presence it does not provide GPS coordinates and `places` may not show any location. 
> 
> 
> 
> If this is not your scenario, can you please [enable debug logging](https://github.com/custom-components/places/blob/master/CONTRIBUTING.md#enable-debug-logging-in-home-assistant) and post these so I can investigate further.

Thanks. Person entity, both are associated to separate iPhones that have the Home Assistant app.

**Comment by kmanan** [comment]
Bump

**Comment by Snuffy2** [comment]
Not sure what you are bumping. As posted previously, I am unable to assist further without debug logs.

**Comment by kmanan** [comment]
> Not sure what you are bumping. As posted previously, I am unable to assist further without debug logs. 

Ah ok, didn't see the note for debug logs. I thought more users who were seeing this. I'll turn on debug mode when I step out and share what is generated

**Comment by DubhAd** [comment]
https://github.com/home-assistant/architecture/discussions/1106 appears to be related

**Comment by Snuffy2** [comment]
@DubhAd as this issue started in May, I don't believe this is the same issue you linked to (and fixed in places with v2.7.1).

It is possible it is related to https://github.com/home-assistant/core/issues/121214 (https://github.com/home-assistant/core/issues/117263) which is apparently fixed in HA 2024.8 but without debug logs and/or additional details I'm not sure.

**Comment by ildar170975** [comment]
I have NO issues with showing History.
2024.7.1, installed immediately after 2024.6.x; also immediately installed the latest update of Places.
Settings of Recorder:
```
recorder:
  auto_purge: true
  purge_keep_days: 30

  exclude:
    domains:
      ...
    entities:
      ...
    entity_globs:
      - sensor.place_*
```

**Comment by kmanan** [comment]
> Not sure what you are bumping. As posted previously, I am unable to assist further without debug logs. 

I think I figured it out. I commented out recorder settings in config.yaml at some point so it wasn't saving. I think it's fixed now, will test. Thanks
