### ISSUE TITLE
Place entity value not updated to Home

### ISSUE THREAD

**Issue by pedropombeiro** [custom-components/places#284]
I have `person` entities that are made up by the iCloud3 sensor and the UniFi router sensor. When a person enters home, it is detected by the router and that causes the `person` entity to be seen as `home`. However, the respective `place` entity is never updated and still points to the last geocoded location.

**Comment by Snuffy2** [comment]
That is due to the way that router device_trackers work. They don't have lat/long in their attributes for places to get a location from. I'd recommend changing the places sensor to just use the iCloud3 device_tracker and not your person entity.

**Comment by pedropombeiro** [comment]
> I'd recommend changing the places sensor to just use the iCloud3 device_tracker and not your person entity.

That's what I did initially, but I wanted to use the router device tracker to allow HA to more quickly recognize when someone arrives home (without constantly polling iCloud for position updates). In any case, this is not a big deal - I was just wondering if it was a bug in the implementation, so I'll close this issue. Thanks for the explanation!
