### ISSUE TITLE
display_options are not applied when device/person is in known HA zone

### ISSUE THREAD

**Issue by pkejval** [custom-components/places#294]
When device/person in in known zone, display_options are not taken into mind and zone name is always used. 
Is this bug or I have error in configuration? I tried with "city", "city_clean", "street", and "town,city,city_clean" - always showed zone name instead.

![obrazek](https://github.com/user-attachments/assets/c266605e-5635-483a-806e-fee1a5c9fa01)

**Comment by pkejval** [comment]
But if I use Advanced Display Options like this `city[postal_town]`... tadaaaa, city is shown instead of zone name! :)

**Comment by Snuffy2** [comment]
Yep, you got it. Glad you figured it out!
