### ISSUE TITLE
Uppercase for zone home

### ISSUE THREAD

**Issue by TeHashX** [custom-components/places#35]
Hi, it's possible to have exact zone name or zones to begin with capitalized letters, ex. Home now is home.
![Screenshot 2022-02-07 221405](https://user-images.githubusercontent.com/1405188/152864850-dfd32268-1f32-435d-af61-16b7fb61814d.jpg)

**Comment by TeHashX** [comment]
I solved somehow, I created another template sensor:
`- platform: template
  sensors:
    brad:
      friendly_name: Brad
      value_template: >-
        {{ states("sensor.places_brad")[0:1] | upper }}{{ states("sensor.places_brad")[1:] }}`

This annoying issue is only for zone home, can be done directly by modifying somem lines in sensor.py?

**Comment by StaleLoafOfBread** [comment]
I think that the source of this issue is this line here https://github.com/custom-components/places/blob/acb59b8f3f6aad6d467bb116251054ed4cbedf13/custom_components/places/sensor.py#L330

Though I don't have the time right now to test that out. Not sure if @juan11perez did that intentionally or not but I agree that the zone name should use the original casing.

**Comment by TeHashX** [comment]
No, it's not that line, I modified in  "self._home_zone = home_zone.upper()" and no change

**Comment by Snuffy2** [comment]
Not exactly a fix, but a new attribute that should display how you want. #48

**Comment by dallas6672** [comment]
Adding .title() to Line 725 should make it display as "Home"...

`new_state = devicetracker_zone.title()`

May also want to add it to Line 722 (haven't tested this one yet)...

`new_state = ', '.join( item.title() for item in user_display )`

**Comment by Snuffy2** [comment]
Add display option of zone_name in v2.0 which will capitalize correctly

**Comment by TeHashX** [comment]
Sorry, but it's still in lowercase in v2.0

**Comment by Snuffy2** [comment]
> Sorry, but it's still in lowercase in v2.0

Did you change the options to use `zone_name` instead of `zone`? If so and it is still showing as lowercase, please [turn on debug logging](https://github.com/custom-components/places/blob/master/CONTRIBUTING.md#enable-debug-logging-in-home-assistant) and post the logs.

**Comment by TeHashX** [comment]
Updated to v2.2, log in attachment
[places.log](https://github.com/custom-components/places/files/9623951/places.log)

**Comment by Snuffy2** [comment]
Ok v2.0.3 has a kludgy fix that should make the zone_name appear in Title case if it is in all lowercase. 
Out of curiosity, is the friendly_name for zone.home lowercase "home" or "Home"?

![SNAG-1001](https://user-images.githubusercontent.com/6526076/191833667-08ffb4d7-68c4-4805-b730-d798fc27ae6c.png)

**Comment by TeHashX** [comment]
Friendly name shows in uppercase
![home](https://user-images.githubusercontent.com/1405188/191932228-f92f4e77-ebde-4aa8-ae96-85daf6c714ab.png)
Sensor
![home2](https://user-images.githubusercontent.com/1405188/191932277-6c3d24d9-5a65-4118-8838-b6940d4f8ed3.png)

But still in lowercase!

**Comment by TeHashX** [comment]
Starting with v2.0.5, if I'm using zone_name or formatted_place it's ok, thank you.

**Comment by TeHashX** [comment]
Can you please fix it with formated_address too? formatted_place doesn't offer enough details, thanks.

**Comment by Snuffy2** [comment]
formatted_address doesn't show the zone. It is the address as determined by OpenStreetMaps and has no knowledge of Home Assistant zones. What do you have in the options field?

**Comment by TeHashX** [comment]
Option field has "formatted_address" only, if I put "zone_name,formatted_address" will show Not_Home, and desired formatted address.

**Comment by Snuffy2** [comment]
Ok. To further clarify as I'm getting hazy on what it used to do. If you previously just had formatted_address in the Options, and you were in a zone, would it display:
zone, formatted_address (ex. `home, 123, Somewhere St, Lincoln, NE, 90210`)
or just zone (ex. `home`)

**Comment by TeHashX** [comment]
With formatted_address when I'm home, will show just home (in lowercase)

**Comment by Snuffy2** [comment]
This should be fixed in v2.2.0 released in the next day or 2.

**Comment by TeHashX** [comment]
I confirm, it's working nice with v2.2.0, thanks for your great work!
