### ISSUE TITLE
Consider mapping wikidata keys, OSM IDs in OSM responses

### ISSUE THREAD

**Issue by CloCkWeRX** [custom-components/places#36]
Example entity:
https://www.openstreetmap.org/way/183931658
https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=183931658&class=shop

Wikidata: Though not always present; this lets further queries be executed against other APIs.

IE:
*  https://www.wikidata.org/wiki/Special:EntityData/Q4681666.json all attributes from wikidata
* https://query.wikidata.org/

This would allow (seperate) sensors like: "X has entity Y, run query to determine architect from wikidata" or similar attributes which are not in OSM.

**Comment by Snuffy2** [comment]
Do you just want the osm ID and osm type in the places attributes or other details from the wiki data added into the attributes?

**Comment by CloCkWeRX** [comment]
I'd maybe put this as either a:
- external_identifiers collection, with a bunch of IDs and values (osm_id, osm_type, wikidata_id), OR
- just dump all of the attributes into an extended_metadata (dump all OSM attibutes in, like brand:wikidata:id)

Use cases samples:

1) Brand recognition. Fire an event when detected at a service station. If extended_metadata && brand = (id for OTR); push notification to android phone, did you want to open app com.ontherun.whatever?

2) Ethical brand ownership. As above, but based on wikidata:brand:id. Event handler this time does a sparql query, return all parent companies, owners. If parent company ownership includes XYZ, push notification: "Warning: you are interacting with XYZ company".
(Think things like the Bye Rupert adblock rulesets, for example)

3) Historic tour prompts. You walked into monument X. Wikipedia:en text summary is ....
Built by person Y.
Built about 1832.

**Comment by Snuffy2** [comment]
I think I have it working, but I'm still doing some testing. However, I've made a number of other changes and ran it through Black Code Formatting. At this point, a PR back to here would be nearly a full change of code, albeit mostly formatting changes. Happy to do it if @iantrich would like me to, but I'm also not sure how active he is on this Repo anymore.

For now, feel free to take a look at my fork if you're interested. [https://github.com/Snuffy2/places](url)

**Comment by CloCkWeRX** [comment]
Neat! Will take a bit of a look
