### ISSUE TITLE
Using person type entity

### ISSUE THREAD

**Issue by sheminasalam** [custom-components/places#37]
Will it be possible to use person entity instead of device tracker? I am using both life360 and HA app for location tracking which is combined with person domain but i not able to make this integration work with person.

**Comment by jurekam** [comment]
I came here looking for the same information.  I now also use multiple trackers per person and use the person entity.  Places is the only component I use that doesn't seem to work with it.  Please implement this capability.

**Comment by Pirol62** [comment]
I support that. My use case: 
I have two mobile phones which I use on different situations (Working week, weekend or holiday).
I managed to make all sensors and notifications flexible and use the current mobile I added to the person entity.
Only the places sensor has to be modified by coding.

**Comment by StaleLoafOfBread** [comment]
I only just started using "places" so I don't know what changed but I can confirm that with 
```
Home Assistant Core 2022.6.5
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1
Places 1.12
```
that using a person entity works. I think this was changed in a recent home assistant update where the person entity now has the proper properties to be a drop in replacement for a tracker though I do not know that for sure; that's just my guess based off what I remember from the live stream some time ago.

**Comment by sheminasalam** [comment]
I think its working now. thanks for the info.
