### ISSUE TITLE
the google map in attrutes to locate a person or a car is no longer shown

### ISSUE THREAD

**Issue by villaniclaudio8** [custom-components/places#47]
hello I was using this feature to track as well as via telegram message which also works very well on the google map which hasn't worked for some time. I explain myself better when I go to attributes to locate the car hours I no longer see the map but only latitude and longitude in terms of values ​​instead before the google map opened I would not want all these changes and new home assistant releases to have spoiled something to the places functionality

**Comment by Snuffy2** [comment]
I don't believe anything had changed in places from Jan 2022 to August 2022. Are you still having issues? You could try v2 to see if it is working better.

**Comment by Snuffy2** [comment]
Closing for now. Please open a new issue if needed.
