### ISSUE TITLE
View in miles/mph instead of km/kph

### ISSUE THREAD

**Issue by shirasp** [custom-components/places#49]
I have been trying to figure out if there is a way to change the settings to show distance and speed in imperial instead of metric units? Is this possible? Thanks!

**Comment by Snuffy2** [comment]
Places doesn't show speed but miles could be added as distance attributes. Would that work?

**Comment by shirasp** [comment]
Yes, that would be great! Basically, anywhere km or meters is listed, the option to change to imperial would be much appreciated!
