### ISSUE TITLE
New 2.0 version: during "migration" a wrong "devicetracker_id" was set - which was not defined in yaml settings by a User

### ISSUE THREAD

**Issue by ildar170975** [custom-components/places#55]
Here was my code in yaml:
```
  - platform: places
    name: place_ipad_air_2
    devicetracker_id: sensor.tracker_common_ipad_air_2
    home_zone: zone.home
    api_key: *******************************
    options: formatted_address
    map_provider: google
    map_zoom: 19
    scan_interval: 60
```
Because of unknown reasons the "devicetracker_id" was replaced with other value.
Here are UI settings:
![image](https://user-images.githubusercontent.com/71872483/191164778-f83d2d5c-86f4-4610-8950-8a61aa710a6b.png)
Here for "Device tracker ID" a friendly_name is displayed - a confusing functionality repeated in many HA UI fields.
Let's tap on on it - otherwise it is impossible to guess what the values it is:

![image](https://user-images.githubusercontent.com/71872483/191165142-e1ee3073-fe6b-4f3e-b67a-dda63af5995e.png)

Why this value was set??? This is not my setting.

**Comment by Snuffy2** [comment]
In the YAML, you were using a sensor as the devicetracker_id and not a device_tracker? Did that work? The previous code was supposed to limit it to only using entities of the device_tracker type but it may not have worked correctly. v2 is limiting it to only device_tracker types. If you or others have it working with sensors as well, I could modify it to support sensors too. The options for the devicetracker_id would get significantly longer, but if it works ....

**Comment by ildar170975** [comment]
I was not obliged to use a device_tracker.
Any entity with latitude & longitude may be used as a source.

**Comment by ildar170975** [comment]
Btw, using a `person` entity as a source is an absolutely reasonable thing.
A `person` entity may have several associated `device_tracker`'s - some of `router` type, some of `gps` type.
And then surely a `person` entity should be set as a source for the "places" sensor.

**Comment by ildar170975** [comment]
And please (!!!) - do not not show a "friendly_name" in the "devicetracker_id" field.

Also probably the title of the field should be renamed to "source id"...
Anyway nobody will see the internals since you deprived users from yaml settings.

**Comment by ildar170975** [comment]
> The options for the devicetracker_id would get significantly longer, but if it works ....

No need to list ALL sensors.
1. `sensor` - only with latitude & longitude.
2. `device_tracker` - only of "gps" type. From other side,, the entity may be unavailable at this moment and may have "-" as a type...
3. `person`
