### ISSUE TITLE
New 2.0 version: cannot specify "scan_interval"

### ISSUE THREAD

**Issue by ildar170975** [custom-components/places#56]
No option for a "scan_interval" in UI settings.
If "scan_interval" does not work anymore - please let us know.

**Comment by Snuffy2** [comment]
From the v1.12 code, scan_interval was never actually setup. There was some setup to accept scan_interval as an option but it didn't do anything.

**Comment by ildar170975** [comment]
Till some version, the `scan_interval` seemed to work - tested with changing it.
Do not know till what version exactly...
What is a default frequency now?

**Comment by Snuffy2** [comment]
Looking a v1.4 which is the earliest in the release list, scan_interval didn't do anything. Anyway, places is using the platforms default scan_interval (The device_tracker scan_interval appears to be 12 seconds). But, it then sets a throttle of 10 min. So, places will run a routine update every 10 min or longer if the platforms scan_interval is >10 min.

**Comment by ildar170975** [comment]
> But, it then sets a throttle of 10 min

Could you explain how does it affect on results?
Consider 2 cases:
1. A monitored entity (person, device_tracker, sensor - [as we discussed here](https://github.com/custom-components/places/issues/55)) is moving, a real address is changed every 1 minute.
2. A monitored entity stays at one place.

**Comment by Snuffy2** [comment]
1. This is a separate trigger. When the state of the devicetracker_id changes, it triggers the places sensor to update. AFAIK there isn't any throttle on this.
2. This when it will run every 10 min

**Comment by ildar170975** [comment]
> 1. When the state of the devicetracker_id changes, it triggers the places sensor to update.

When a tracker is moving and still is not in any zone, it's state is always "not_home".
Does it mean that "places" are not updated?



> 1. internal throttling

What is a "throttle" in a device_tracker context?



> 2. This when it will run every 10 min

To be sure - when a tracker is inside some zone (and not "not_home"), it's state does not change - and then "places" are updated every 10 minutes? And what is a reason of updating "places" if the tracker still in same zone?

**Comment by Snuffy2** [comment]
> When a tracker is moving and still is not in any zone, it's state is always "not_home". Does it mean that "places" are not updated?

No, attribute (like latitude and longitude) updates also trigger the update

> What is a "throttle" in a device_tracker context?

Not sure I understand the question. Throttle is not really visible or able to be set by the user for any built in device types. A custom integration could expose the option to set the throttle or scan_interval times (as places seemed to have done in the past).

> To be sure - when a tracker is inside some zone (and not "not_home"), it's state does not change - and then "places" are updated every 10 minutes? And what is a reason of updating "places" if the tracker still in same zone?

Places checks to see if it needs to update every 10  min:
1. If the devicetracker coordinates are identical from previous to now, the update stops
2. If the coordinates are different but the distance is <10m, the update stops
3. If there are >3 checks with distance <10m, it will proceed to next check
4. If the distance is >10m it will requery OSM. If the previous state = new state, the update stops
5. If it gets to here, the full update is run and an event is fired

**Comment by ildar170975** [comment]
> Not sure I understand the question

I asked because I just do not know what throttle is.
For instance, in mechanisms a "throttle" is a kind of "safety device" - like "open a valve if a pressure reaches 4 hPa".

> Places checks to see if it needs to update every 10 min:

I see, a complex logic. Thank you for describing it.

> No, attribute (like latitude and longitude) updates also trigger the update

Very good.


----------------

Finally, I got answers about `scan_interval`. The issue may be closed then.
Thank you very much for explanations!
