### ISSUE TITLE
ValueError: could not convert string to float: 'None'

### ISSUE THREAD

**Issue by jebeke65** [custom-components/places#6]
distance_m = distance(float(new_latitude), float(new_longitude), float(home_latitude), float(home_longitude))
ValueError: could not convert string to float: 'None'

Someone has this error also ?

**Comment by emouawad** [comment]
Yes and for quiet some time!
Have you been able to solve it?

**Comment by alandtse** [comment]
It's because there's some bad longitude or latitude data being collected and there's no error checking before it tries to do math on it. Checking if there's a robust way to fix it.

**Comment by iantrich** [comment]
We could add a check that all lat/lon values are actual numbers using https://www.w3schools.com/jsref/jsref_isnan.asp

**Comment by alandtse** [comment]
@iantrich Yes, but you're using a javascript reference for a python bug. I have a fix I'll submit a PR for but it basically disabled the entire update while the lat/long are None. Not sure what the second order effects are of that.

**Comment by iantrich** [comment]
🤦‍♀️ was doing lots of js dev last night
