### ISSUE TITLE
Problem after updating Places to 2.0 & 2.0.1

### ISSUE THREAD

**Issue by 03397** [custom-components/places#61]
After upgrading to the above versions I am getting the following errors from home assistant.
Reverting back to 1.12 solves the issue.
I have the following in my configuration

- platform: places
  name: nicolas_places
  devicetracker_id: device_tracker.nicolasmobile
  options: zone, place
  map_provider: google
  map_zoom: 18
  language: en
  home_zone: zone.home
  api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxx
- platform: places
  name: angela_places
  devicetracker_id: device_tracker.angelamobile
  options: zone, place
  map_provider: google
  map_zoom: 18
  language: en
  home_zone: zone.home
  api_key: xxxxxxxxxxxxxxxxxxxxx

2022-09-21 18:41:05.920 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.places.sensor
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 681, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 698, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/places/sensor.py", line 131, in <module>
    discovery_info: DiscoveryInfoType | None = None,
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'NoneType'

**Comment by Snuffy2** [comment]
Please see if v2.0.2 fixes this error. I've not been able to reproduce it. I copied your config from above and changed it to valid device_trackers and they loaded fine. However, the | operator does seem weird there (I had copied it from other integrations) so I made a small change.

If you are still getting the error with v2.0.2 or greater, please [enable debug logging](https://github.com/custom-components/places/blob/master/CONTRIBUTING.md#enable-debug-logging-in-home-assistant) and re-post the logs before, including and after the error.

**Comment by 03397** [comment]
Now, updated to version 2.0.3
New error
[YAML Import] Not importing: devicetracker_id: device_tracker.nicolasmobile doesn't exist
[YAML Import] Not importing: devicetracker_id: device_tracker.angelamobile doesn't exist

**Comment by Snuffy2** [comment]
Sorry for the dumb question, but are those valid device_trackers? That error fires when it can't find the device_tracker in the Home Assistant StateMachine (aka. list of Home Assistant valid entities).

**Comment by 03397** [comment]
Yes they are. They are gps logger trackers
My guess is that the places loads before these are loaded and throws an error.
I do not know why this was not happening before the upgrade.

**Comment by Snuffy2** [comment]
I am waiting for HA to start before adding the sensor but it turns out I'm not waiting for HA to load before doing the import validation. Will move the import validation until after HA load to see if that helps. #88

**Comment by Snuffy2** [comment]
Please see if v2.0.4 fixes this.

**Comment by 03397** [comment]
New error now. The other errors appeared once but after second restart after the update they were disappeared. 
Error initializing 'websocket_api' trigger: In 'numeric_state' condition: unknown entity sensor.nicolas_places

**Comment by Snuffy2** [comment]
Can you please [enable debug logging](https://github.com/custom-components/places/blob/master/CONTRIBUTING.md#enable-debug-logging-in-home-assistant) and post the log with the debugging and the full traceback of the error.

**Comment by 03397** [comment]
After second restart error disappeared.

**Comment by Snuffy2** [comment]
Ok, please open a new issues if any further issues arise.
