### ISSUE TITLE
Cannot "Submit" a settings' form even w/o any changes

### ISSUE THREAD

**Issue by ildar170975** [custom-components/places#67]
ver 2.0.2.

Select any entry in the settings panel which has a "devicetracker_id" set to "person":
![image](https://user-images.githubusercontent.com/71872483/191657943-5bae5f69-57e7-4b97-aa17-69519e011dd4.png)

Press the "Submit" button:
![image](https://user-images.githubusercontent.com/71872483/191658002-57c3fae0-3458-4e7a-87e1-f5adcd3781d2.png)

**Comment by Snuffy2** [comment]
I'll put out v2.0.3 that will hopefully improve this. I changed the logic to accept all device_tracker and person entity types. Only the sensor entity types will be filtered to only accept those with latitude/longitude attributes.

**Comment by ildar170975** [comment]
Is 2.0.3 not released yet?
