### ISSUE TITLE
After upgrade to >2.0, Error: Platform not found

### ISSUE THREAD

**Issue by pissten** [custom-components/places#68]
2022-09-22 08:59:00 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform places.sensor: Platform not found (No module named 'homeassistant.helpers.issue_registry').

**Comment by Snuffy2** [comment]
What version of Home Assistant are you on? It looks like that module was moved in a recent version. I may need to check Home Assistant version and then look in the prior location as well.

**Comment by Snuffy2** [comment]
v2.0.3 will hopefully fix this. It will look in prior location for the issue_registry if it's not in the new location.

**Comment by pissten** [comment]
@Snuffy2 
Thanks for getting into this so quickly..
Sadly i'm still facing troubles after updating to the newest version. Now i'm getting another error:
`ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform places.sensor: Platform not found (No module named 'homeassistant.components.repairs')`

**Comment by Snuffy2** [comment]
Ok, I'll try another approach then

**Comment by Snuffy2** [comment]
If you are able to, please try beta/pre-release v2.0.3.2. I tried a different approach to bypassing the issue registry in Home Assistant versions <2022.9

[How to enable beta versions for an integration in HACS](https://hacs.xyz/docs/faq/beta/)

**Comment by pissten** [comment]
Thank you very much! This solves it for me 👌👍
________________________________

**Comment by Snuffy2** [comment]
Great to hear, will add it to the next release.
