### ISSUE TITLE
New sensor is created after each reboot of HA

### ISSUE THREAD

**Issue by mvunen** [custom-components/places#73]
1. Since the new versions Places is creating a new sensor after each reboot of HA... Currently I have 40 new sensors in total for 2 persons. 
2. In the logging I also see a connection limit reach error... So I will look again tomorrow, but the connection thing is another issue I think....
3. The new created sensor keeps Initializing... (this probably is caused by issue 2

**HA Version information:**
> Home Assistant 2022.9.0
> Supervisor 2022.09.1
> Operating System 8.5
> Frontend 20220907.0 - latest
> 

**My config in configuration.yaml**
> sensor places_xxxxxxx:
>   - platform: places          #ignore the bullet symbol... this is a dash in my config
>     name: xxxxxx_locatie
>     devicetracker_id: device_tracker.iphonexxxxxx
>     #options: street, street_number, city
>     map_provider: google
>     map_zoom: 19
>     home_zone: zone.home
>     api_key: 'xxxxxxx@xxxxxxxx.nl'

I did not had this behavior in 2 versions earlier.
Did I do something wrong? What can I do to fix this? Maybe this is caused by a misconfiguration from my side, I'm relatively new to HA.

Thanks for this nice plugin and the energy you stick in this free module!

**Part of the error in logging:**
> Logger: homeassistant
> Source: custom_components/places/sensor.py:993
> Integration: Places: OpenStreetMap Sensor ([documentation](https://github.com/custom-components/places), [issues](https://github.com/custom-components/places/issues))
> First occurred: 22:57:38 (6 occurrences)
> Last logged: 23:05:45
> 
> Error doing job: Future exception was never retrieved
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
>     conn = connection.create_connection(
>   File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
>     raise err
>   File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
>     sock.connect(sa)
> OSError: [Errno 101] Network unreachable
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
>     httplib_response = self._make_request(
>   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
>     self._validate_conn(conn)
>   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
>     conn.connect()
>   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
>     self.sock = conn = self._new_conn()
>   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
>     raise NewConnectionError(
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fedb9cadff0>: Failed to establish a new connection: [Errno 101] Network unreachable
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
>     resp = conn.urlopen(
>   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
>     retries = retries.increment(
>   File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /reverse?format=jsonv2&lat=52.58351869210295&lon=5.931531429159805&accept-language=nl&addressdetails=1&namedetails=1&zoom=18&limit=1&email=martijn@van-unen.nl (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fedb9cadff0>: Failed to establish a new connection: [Errno 101] Network unreachable'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/places/sensor.py", line 548, in tsc_update
>     self.do_update("Track State Change")
>   File "/config/custom_components/places/sensor.py", line 993, in do_update
>     osm_response = requests.get(osm_url)
>   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
>     return request("get", url, params=params, **kwargs)
>   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /reverse?format=jsonv2&lat=52.58351869210295&lon=5.931531429159805&accept-language=nl&addressdetails=1&namedetails=1&zoom=18&limit=1&email=martijn@van-unen.nl (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fedb9cadff0>: Failed to establish a new connection: [Errno 101] Network unreachable'))

**Comment by Snuffy2** [comment]
Please see if v2.0.3 is more graceful in handling the Connection Errors.

As for the duplicate sensors on every restart, if the sensors remain in the configuration.yaml after they are imported/upgraded, the config_flow logic built into Home Assistant tries to import it on every start. Because the places sensor did not have a unique ID in versions before v2, I had to create a pseudo-unique ID to try to identify and prevent previously imported sensors in configuration.yaml from being imported again.

I re-enabled some additional debug logging with v2.0.3. After upgrading, can you please 
[enable debug logging](https://github.com/custom-components/places/blob/master/CONTRIBUTING.md#enable-debug-logging-in-home-assistant) and post the logs so I can see if I can sort out what is happening.

**Comment by Snuffy2** [comment]
I've also found the issue with some places sensors not updating and staying at "Initializing..." Also in v2.0.3 hopefully released tonight.

**Comment by mvunen** [comment]
Thanks for you quick actions!!
Before updating to the new version:
- Removed the sensors from configuration.yaml ==> resulting in no more extra added sensors after reboot => thanks!!
- After a while (the next day) I think the connection was restored (within limit of connection amount) address is visible I thought.... 

After updating to new version:
- Everything still works fine and now I can see the address is also updating again.. before update always home or another address was visible. I think the new version fixed that!

I also enabled logging... still interested in receiving these logs?  If so, where do I find the logs you need? thanks!

**Comment by Snuffy2** [comment]
No, if you took the sensors our of the configuration.yaml and everything is working well, I don't need any logs, but thanks! You can remove the debug logging settings from your configuration.yaml too.
