### ISSUE TITLE
Do not show "friendly_name" in settings, show "entity_id"

### ISSUE THREAD

**Issue by ildar170975** [custom-components/places#91]
In settings:

![image](https://user-images.githubusercontent.com/71872483/192415363-3a40fbdb-fbfd-47a0-9fd6-125eecdf34f0.png)

I have plenty of entities with same "friendly_name".
It is absolutely unclear which entity is used as `devicetracker_id`.
Please replace it with "entity_id".

**Comment by Snuffy2** [comment]
v2.2.0 will show: `friendly_name (entity_id)` Likely released in the next day or 2.
<img width="449" alt="2022-10-11_21-17-34 720" src="https://user-images.githubusercontent.com/6526076/195226877-e595c19e-d2f3-4118-8f2c-9ca0df271969.png">
